name: work_order_app
description: The Official Black Sheep Company Work Order App.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  intl: ^0.18.0
  table_calendar: ^3.0.9
  lucide_icons: ^0.257.0
  image_picker: ^1.0.4
  firebase_core: ^3.11.0
  firebase_auth: ^5.5.0
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
